{
 "title": "Telemetry",
 "description": "test",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "MovingAverageScore",
    "label": "MovingAverageScore",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "# Title\n\nAquí explicaré cosas"
   }
  },
  {
   "title": "Anomaly Score",
   "type": "timeseries",
   "description": "To fill",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp\n| filter log_type = 'telemetry_data'\n| display anomaly_score, @timestamp ",
     "logGroups": [
      {
       "accountId": "730335312484",
       "arn": "arn:aws:logs:eu-west-1:730335312484:log-group:/aws/lambda/iss-telemetry-analyzer-lambda:*",
       "name": "/aws/lambda/iss-telemetry-analyzer-lambda"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Moving AVG Score std",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp\n| sort @timestamp desc\n| filter log_type = 'telemetry_data'\n| limit 1\n| display moving_avg_std, @timestamp ",
     "logGroups": [
      {
       "accountId": "730335312484",
       "arn": "arn:aws:logs:eu-west-1:730335312484:log-group:/aws/lambda/iss-telemetry-analyzer-lambda:*",
       "name": "/aws/lambda/iss-telemetry-analyzer-lambda"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Moving average Anomaly Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp\n| sort @timestamp desc\n| filter log_type = 'telemetry_data'\n| limit 1\n| display moving_avg_score, @timestamp ",
     "logGroups": [
      {
       "accountId": "730335312484",
       "arn": "arn:aws:logs:eu-west-1:730335312484:log-group:/aws/lambda/iss-telemetry-analyzer-lambda:*",
       "name": "/aws/lambda/iss-telemetry-analyzer-lambda"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Anomaly Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp\n| sort @timestamp desc\n| filter log_type = 'telemetry_data'\n| limit 1\n| display anomaly_score, @timestamp ",
     "logGroups": [
      {
       "accountId": "730335312484",
       "arn": "arn:aws:logs:eu-west-1:730335312484:log-group:/aws/lambda/iss-telemetry-analyzer-lambda:*",
       "name": "/aws/lambda/iss-telemetry-analyzer-lambda"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ISS External Cooling Loop A",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expression": "fields @timestamp\n| filter log_type = 'telemetry_data'\n| display flowrate, pressure, temperature, @timestamp ",
     "logGroups": [
      {
       "accountId": "730335312484",
       "arn": "arn:aws:logs:eu-west-1:730335312484:log-group:/aws/lambda/iss-telemetry-analyzer-lambda:*",
       "name": "/aws/lambda/iss-telemetry-analyzer-lambda"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expression": "fields @timestamp\n| filter log_type = 'telemetry_data'\n| display temperature, @timestamp ",
     "logGroups": [
      {
       "accountId": "730335312484",
       "arn": "arn:aws:logs:eu-west-1:730335312484:log-group:/aws/lambda/iss-telemetry-analyzer-lambda:*",
       "name": "/aws/lambda/iss-telemetry-analyzer-lambda"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Flowrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kg/hr" } },
   "targets": [
    {
     "expression": "fields @timestamp\n| filter log_type = 'telemetry_data'\n| display flowrate, @timestamp ",
     "logGroups": [
      {
       "accountId": "730335312484",
       "arn": "arn:aws:logs:eu-west-1:730335312484:log-group:/aws/lambda/iss-telemetry-analyzer-lambda:*",
       "name": "/aws/lambda/iss-telemetry-analyzer-lambda"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Pressure (mmHg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mmHg" } },
   "targets": [
    {
     "expression": "fields @timestamp\n| filter log_type = 'telemetry_data'\n| display pressure, @timestamp ",
     "logGroups": [
      {
       "accountId": "730335312484",
       "arn": "arn:aws:logs:eu-west-1:730335312484:log-group:/aws/lambda/iss-telemetry-analyzer-lambda:*",
       "name": "/aws/lambda/iss-telemetry-analyzer-lambda"
      }
     ],
     "queryLanguage": "CWLI",
     "queryMode": "Logs",
     "region": "eu-west-1",
     "statistic": "Average"
    }
   ]
  }
 ]
}